name: Test
on: push

jobs:
  test:
    run-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Verify hello action works
        uses: ./